project:
  type: website

website:
  title: "Derna EvacuConnect"
  navbar:
    logo: "/pictures/logo.png"
    left:
      - overview.qmd
      - proposal.qmd
      - methodology.qmd
      - results.qmd
      - lessons.qmd
      - more.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
