project:
  type: website

website:
  favicon: "/pictures/favicon.png"
  navbar:
    logo: "/pictures/favicon.png"
    title: "Derna EvacuConnect" 
    left:
      - text: Overview
        href: index.qmd
      - proposal.qmd
      - text: Results & Discussion
        href: results.qmd
      - text: Poster
        href: poster.qmd
      - text: Lessons Learnt
        href: lessons.qmd
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    linkcolor: rgb(0, 153, 255)
    toc: true
