project:
  type: website

website:
  title: "SMT201_Grp5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - proposal.qmd
      - methodology.qmd
      - results.qmd
      - lessons.qmd
      - about.qmd
      - more.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

