project:
  type: website

website:
  favicon: "/pictures/logo.png"
  navbar:
    logo: "/pictures/prof.png"
    title: "Derna EvacuConnect" 
    left:
      - text: Overview
        href: index.qmd
      - proposal.qmd
      - methodology.qmd
      - results.qmd
      - lessons.qmd
      - more.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
