project:
  type: website

website:
  favicon: "/pictures/favicon.png"
  navbar:
    logo: "/pictures/mugshots/prof.png"
    title: "Derna EvacuConnect" 
    left:
      - text: Overview
        href: index.qmd
      - proposal.qmd
      - methodology.qmd
      - text: Results & Discussion
        href: results.qmd
      - text: Poster
        href: poster.qmd
      - report.qmd
      - text: Lessons & Reflections
        href: lessons.qmd
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
