project:
  type: website

website:
  favicon: "/pictures/logo_bg.png"
  navbar:
    title: "Derna EvacuConnect" 
    left:
      - overview.qmd
      - proposal.qmd
      - methodology.qmd
      - results.qmd
      - lessons.qmd
      - more.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
