---
title: "Project Proposal"
---
___

### Motivation of project

In the recent collapse of the Derna dam following intense rainfall, there was a high casualty count in the city of Derna due to a major flood. We decided to analyse and assess the accessibility of Derna City’s evacuation centres and medical services to evaluate the changes in the extent of such facilities effectiveness in rendering aid and medical services in an aftermath of a disaster such as the flood.

### Project objective

Based on our motivation, we have 2 main objective for our project:

1. To find out the accessibility of Derna city’s evacuation centres and medical services. 

2. To find out how disaster-proof the accessibility to the evacuation centres and medical services are.

### Data

- [OSM Libya](https://download.geofabrik.de/africa/libya.html) from Geofabrik
  - [Pre-flood OSM data (23-09-01)](https://download.geofabrik.de/africa/libya-230901-free.shp.zip)
  - [Post-flood OSM data (23-10-01)](https://download.geofabrik.de/africa/libya-231001-free.shp.zip)
- [Libya Floods](https://data.humdata.org/event/f1c3a777-4079-49fb-9d64-12a72f46f1e3) at Humanitarian Data Exchange portal
  - [Location of Dams](https://data.humdata.org/dataset/dam-locations-east-libya)
  - [Libya Buildings Footprint](https://data.humdata.org/dataset/buildings-footprint-floods-derna-libya)
  - [Libya - 250m hexagonal grid and grid centres over city of Derna](https://data.humdata.org/dataset/250m-hexagonal-gird-over-city-of-derna)
  - [Flood impact assessment in Derna City, East Province, Libya](https://data.humdata.org/dataset/flood-impact-assessment-in-derna-city-east-province-libya)
- [OpenAerialMap](https://openaerialmap.org/)
  - [Pre-flood Satellite Imagery](https://map.openaerialmap.org/#/22.67578125,32.697177359290635,8/square/1221022202/6502b83e0906de000167e696?_k=baen2a)
  - [Post-flood Satellite Imagery](https://map.openaerialmap.org/#/22.67578125,32.697177359290635,8/square/1221022202/65029d220906de000167e685?_k=tourdg)

### Scope of work

**HELP**


- Selection of project focus and conducting literature review.
- Preparing proposal and project website.
- Data collection, extraction, integration, transformation and wrangling.
- Designing and building GIS model and database.
- Performing GIS analysis.
- Preparing poster and project webpage.

^ from prof (idk do we add on more description?)

### Project schedule
